language: cpp
compiler: gcc
dist: xenial
python:
  - "3.6"

addons:
  apt:
    packages:
      cmake
      python-pip
      lcov

install:
  - pip install --user -r requirements.txt
  - bash script/installCMake.sh

script:
  - make -j
  - make -j test