language: cpp
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      cmake
      python-pip
      lcov

install:
  - pip install --user -r requirements.txt

script:
  - make -j
  - make -j install INSTALL_PATH=install
  - make -j test