language: cpp
compiler: gcc
dist: xenial
python:
  - "3.6"

addons:
  apt:
    packages:
      python-pip
      lcov

install:
  - pip install --user -r requirements.txt

script:
  - bash script/installCMake.sh
  - make -j
  - make -j test
