name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install cppcheck xsltproc -y
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: build
      run: make -j test
    - uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: build/test/ctestjunittestresults.xml
    - uses: actions/upload-artifact@v2
      with:
        name: Static Analysis Results
        path: build/test/staticanalysis/cpptest_results.xml
    - uses: ashley-taylor/junit-report-annotations-action@1.3
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
